# Cloud Build - 本番環境用
# トリガー: main ブランチへのプッシュ

steps:
  # ステップ0: 依存関係インストール
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci', '--omit=dev']
    id: 'install'

  # ステップ1: 統合テスト実行（本番環境に対して）
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e  # エラーがあれば即座に停止
        echo "Running integration tests against production..."
        TEST_BASE_URL=https://line-calendar-bot-67385363897.asia-northeast1.run.app npm test
        echo "Tests passed successfully!"
    id: 'test'
    waitFor: ['install']

  # ステップ2: Dockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/line-calendar-bot:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/line-calendar-bot:latest'
      - '.'
    id: 'build'
    waitFor: ['test']

  # ステップ3: Container Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/line-calendar-bot:$COMMIT_SHA'
    id: 'push'
    waitFor: ['build']

  # ステップ4: latestタグもプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/line-calendar-bot:latest'
    id: 'push-latest'
    waitFor: ['build']

  # ステップ5: Cloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'line-calendar-bot'
      - '--image=gcr.io/$PROJECT_ID/line-calendar-bot:$COMMIT_SHA'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-env-vars=LINE_CHANNEL_ACCESS_TOKEN=${_LINE_CHANNEL_ACCESS_TOKEN}'
      - '--set-env-vars=LINE_CHANNEL_SECRET=${_LINE_CHANNEL_SECRET}'
      - '--set-env-vars=GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}'
      - '--set-env-vars=GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}'
      - '--set-env-vars=OAUTH_REDIRECT_URI=${_OAUTH_REDIRECT_URI}'
      - '--set-env-vars=GEMINI_API_KEY=${_GEMINI_API_KEY}'
      - '--set-env-vars=LIFF_ID=${_LIFF_ID}'
    id: 'deploy'
    waitFor: ['push']

images:
  - 'gcr.io/$PROJECT_ID/line-calendar-bot:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/line-calendar-bot:latest'

substitutions:
  _LINE_CHANNEL_ACCESS_TOKEN: ''
  _LINE_CHANNEL_SECRET: ''
  _GOOGLE_CLIENT_ID: ''
  _GOOGLE_CLIENT_SECRET: ''
  _OAUTH_REDIRECT_URI: ''
  _GEMINI_API_KEY: ''
  _LIFF_ID: ''

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '600s'

tags:
  - 'production'
  - 'line-calendar-bot'
